//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DataModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCompany()
        {
            this.tblBranches = new HashSet<tblBranch>();
            this.tblDepartments = new HashSet<tblDepartment>();
        }
    
        public int CompanyId { get; set; }

        [Required]
        [StringLength(150,MinimumLength =3,ErrorMessage ="Company Name must be atleast 3 charachters")]
        public string CompanyName { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required]
       
        [RegularExpression(@"^(?=.*[._\-@&*#!?])[A-Z][a-z0-9._\-@&*#!?]{8,15}$")]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBranch> tblBranches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDepartment> tblDepartments { get; set; }
    }
}
